<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17781" started-at="2017-12-21T09:51:21Z" finished-at="2017-12-21T09:51:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17781" started-at="2017-12-21T09:51:21Z" finished-at="2017-12-21T09:51:39Z">
      <class name="com.testingmasters.TestScriptDefinitions.Module1">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="BeforeSuite" is-config="true" duration-ms="172" started-at="2017-12-21T15:21:21Z" finished-at="2017-12-21T15:21:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="BeforeClass" is-config="true" duration-ms="0" started-at="2017-12-21T15:21:21Z" finished-at="2017-12-21T15:21:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="BeforeMethod(java.lang.reflect.Method)[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="BeforeMethod" is-config="true" duration-ms="9620" started-at="2017-12-21T15:21:21Z" finished-at="2017-12-21T15:21:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.testingmasters.TestScriptDefinitions.Module1.TC103()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="TC103()[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="TC103" duration-ms="8076" started-at="2017-12-21T15:21:31Z" finished-at="2017-12-21T15:21:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at com.testingmasters.library.Util.logEvent(Util.java:110)at com.testingmasters.HRMPages.Pg002_HomePage.NavigateTOTime(Pg002_HomePage.java:59)at com.testingmasters.TestScriptDefinitions.Module1.TC103(Module1.java:49)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC103 -->
        <test-method status="PASS" signature="AfterMethod(org.testng.ITestResult)[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="AfterMethod" is-config="true" duration-ms="66" started-at="2017-12-21T15:21:39Z" finished-at="2017-12-21T15:21:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC103 status=FAILURE method=Module1.TC103()[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:com.testingmasters.TestScriptDefinitions.Module1@31610302]" name="AfterSuite" is-config="true" duration-ms="15938" started-at="2017-12-21T15:21:39Z" finished-at="2017-12-21T15:21:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- com.testingmasters.TestScriptDefinitions.Module1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
